spring.application.name=server

spring.datasource.url=jdbc:postgresql://localhost:5433/clinic_queue
spring.datasource.username=clinic_queue_app
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=none

app.cors.allowed-origin=http://localhost:5173

