spring.application.name=server

spring.datasource.url=jdbc:postgresql://localhost:5433/clinic_queue
spring.datasource.username=clinic_queue_app
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=none

app.cors.allowed-origin=http://localhost:5173

jwt.secret=5QXwlzfOx7dnleF53Gbp7eR/iRuEpr//JGz9wMovM48=
logging.level.org.springframework.security=DEBUG
